name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días a la medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Generar animación de la serpiente
        uses: Platane/snk@v2
        with:
          github_user_name: tu-usuario
          outputs: dist/snake.svg

      - name: Subir animación al repositorio
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
